# Generated by Django 5.1 on 2026-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
