# Generated by Django 5.1 on 2026-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetstore', '0002_product_description_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
            ],
            options={
                'verbose_name': 'Accessory / Other',
                'verbose_name_plural': 'Accessories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gadgetstore.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gadgetstore.product',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gadgetstore.product',),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='spec_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
